Menu
maserekafelex/potifolio pull request #7
Opened 2023-07-25 06:46 UTC by BHObserver

sf

2023-07-25 08:05 UTC, shahadat3669 requested changes
Hi @BHObserver @maserekafelex , 

Great job so far! 👏 You've done well, and you're almost there for the next project ⏭️, but there are a few issues 🐛 that you still need to work on.

<img  src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif" />


## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights
✅ No linter Errors
✅ Descriptive PR Title
✅ Descriptive PR Description



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-25 08:05 UTC, shahadat3669 commented on index.html
> +        </div>
👏 Excellent job on implementing the nav items within an unordered list! 👍 I do have a couple of suggestions to further improve your code:

- [ ] Consider wrapping your nav items and the hamburger icon inside a `<nav>` tag. This small adjustment will enhance the semantic structure of your HTML and improve accessibility. 🌐👍

- [ ] Additionally, in the mobile version, I'm unable to see any nav items. Please ensure that your code is updated and functioning correctly, as the nav items should be visible on mobile screens.
![image](https://github.com/maserekafelex/potifolio/assets/55840999/b4165b6a-83b3-4cdc-bb5d-30986d7b72d9)

By incorporating these updates, your code will become even more semantically meaningful and aligned with best practices for HTML. Your attention to detail will undoubtedly make your project shine! 🌟📝🚀 Keep up the great work, and I'm excited to see your project continue to flourish! 💪💻

2023-07-25 08:05 UTC, shahadat3669 commented on index.html
> +        </div>
- [ ] 👍 Great work on adding the close icon! However, based on the design requirements, there should be no background color for the close icon. Please update your code to remove the background color and ensure it matches the design as closely as possible. 🎨

![image](https://github.com/maserekafelex/potifolio/assets/55840999/4e5d6e2f-9090-4387-b15b-5d1ea911cddd)

By making this adjustment, your code will align perfectly with the design guidelines, resulting in a polished and professional look for your project. Keep up the good work! 💪🚀

2023-07-25 11:45 UTC, LionRouge1 requested changes
Hi @BHObserver @maserekafelex, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Suggested changes :recycle: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-07-25 11:45 UTC, LionRouge1 commented on index.html
> +                <a href="/Contact" class="nav-link">Contact</a>
- [ ] These links are broken because we do not have any file named `headlines`, `About` or `Contact` in the project. Therefore I suggest you use **hash navigation** to display the appropriate sections when the user click on an option to follow the project requirement. You can read more about `hash link` [here](https://stackoverflow.com/questions/2835140/how-do-i-link-to-part-of-a-page-hash)
![Screenshot from 2023-07-25 11-27-54](https://github.com/maserekafelex/potifolio/assets/91142432/6a534ea0-0d05-442f-9419-934b6763753f)

E.g. `<a href="#headlines" class="nav-link">Portfolio </a>`

2023-07-25 11:45 UTC, LionRouge1 commented on style.css
> +  }
[OPTIONAL]
- [ ] Nice work implementing the hamburger button :+1: However it is not show on screen with width less than `586px`. kindly reduce the `margin-left` value and make sure the button show all screen less than `768px`

_**This is a requirement of the project but first reviewer didn't notice it. so I requested this as an optional but I highly recommend you to make the change**_

2023-07-25 11:45 UTC, LionRouge1 commented on style.css
> +  }
- [ ] Kindly stick to the figma design as much as possible (e.g., font, colors, images, text, margins). Note the `font-size`, `font-weight` and the margin between options in the Figma design, they are different compared to your design. Kindly check it to follow the project requirement.
### Your design :point_down: 
![Screenshot from 2023-07-25 11-41-12](https://github.com/maserekafelex/potifolio/assets/91142432/55555e43-933c-476e-a7f0-4727ee79a279)
### What it is supposed to look like :point_down: 
![Screenshot from 2023-05-15 17-26-08](https://github.com/maserekafelex/potifolio/assets/91142432/9c7247c4-3476-42c0-b2d6-c971d06da7a0)

2023-07-25 14:23 UTC, anagudelogu requested changes
# STATUS: CHANGES REQUIRED ♻️ 🚧 

Hi @maserekafelex @BHObserver 👋🏼 
I'm Andres.

You've done a great job implementing some of the requested changes for this milestone 🚀, but there are still some which haven't been addressed yet. You're getting closer, keep up the good work! 🤖 🎆 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

 ## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 


 ## Required Changes ♻️
_Check the comments under the review._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-25 14:23 UTC, anagudelogu commented on index.html
> +                <span class="bar"></span>
You did well working on the previous reviewer's requirements. However, some bugs got introduced on the changes you made:

[Screencast from 25-07-23 09:15:11.webm](https://github.com/maserekafelex/potifolio/assets/77069011/456a1b62-3278-4cc7-9d1e-e014a0d8cd4c)

- [ ] The margin-left is so large, that the element doesn't show up on the screen. I would suggest you used a different approach to layout your elements, in this case, as you're using `position: fixed`, I recommend using `top, left, bottom, right` values to position your hamburger instead of margins! 🤓 🔧 


- [ ] Also, If you look at the menu, the links are hidden to the left of the screen, this happens once again because you're using margins to position them. Please consider fixing this! 🤓 🔧

2023-07-26 12:59 UTC, ahmetbozaci commented
Hello @maserekafelex 

_This is a manual review_

- The mobile menu is not responsive. The minimum mobile screen should be 375px. 
![image](https://github.com/maserekafelex/potifolio/assets/38635158/b00b5b54-9ba5-4159-be4e-321b49ebf30d)
![image](https://github.com/maserekafelex/potifolio/assets/38635158/8b6f23e6-e2fb-4a96-a09e-9e1b74b8155f)

- To fix this kindly implement these:

- [ ] Remove `align-item:center` from `nav-menu` class
- [ ] Remove `margin-left: -280px` from `nav-item a` class
- [ ] Give `margin-left: 2rem` from `nav-item` class
- [ ] Remove `margin-left: 34rem` from `hamburger` class and give 18rem margin-left

After that, it should be like that
![image](https://github.com/maserekafelex/potifolio/assets/38635158/587974f0-a271-4fed-a932-999e97ce4ef9)
![image](https://github.com/maserekafelex/potifolio/assets/38635158/dcc1ac17-f646-4530-8e5c-5fa137c80e8d)

2023-07-27 09:55 UTC, merged